language: generic
sudo: required
services: 
    - docker

before_install: 
    - docker build -t minchanjun/dockerPractice -f Dockerfile.dev .

script: 
    - docker run -e CI=true minchanjun/dockerPractice npm run test